version: '3.9'

services:
  db:
    image: mysql:8
    container_name: sige_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sige
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: 
      context: ./sige-api
      dockerfile: Dockerfile
    container_name: sige_api
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./sige-api:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: sige
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@gmail.com
      DJANGO_SUPERUSER_PASSWORD: admin
      DEBUG: "True"
      DJANGO_SECRET_KEY: chave_super_secreta_aqui
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
  app:
    build: 
      context: ./sige-app
      dockerfile: Dockerfile
    container_name: sige_app
    volumes:
      - ./sige-app:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - api
    command: npm start


volumes:
  mysql_data: