# Generated by Django 6.0.2 on 2026-03-14 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lagradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catmat', models.CharField(max_length=6, unique=True)),
                ('descricao', models.CharField(max_length=300)),
                ('unidade_medida', models.CharField(choices=[('KG', 'Quilograma (KG)'), ('G', 'Grama (G)'), ('L', 'Litro (L)'), ('mL', 'Mililitro (mL)'), ('duzia', 'Duzia'), ('cento', 'Cento'), ('PCT', 'Pacote (PCT)'), ('CX', 'Caixa (CX)'), ('FND', 'Fardo (FND)'), ('GAR', 'Garrafa (GAR)'), ('lata', 'Lata'), ('un', 'Unidade (UN)')], default='KG', max_length=5)),
                ('categoria', models.CharField(choices=[('tempS', 'Tempero Secos'), ('SM', 'Secos / Mercearia'), ('Lac', 'Lácteos e Derivados'), ('Oli', 'Óleos, Azeites e Vinagres'), ('MolCo', 'Molhos e Condimentos'), ('Fr', 'Frutas'), ('Le', 'Legumes'), ('Pr', 'Proteínas')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='cadastro.endereco')),
            ],
        ),
    ]
