# Generated by Django 6.0.2 on 2026-09-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgenerico',
            name='conteudo_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemgenerico',
            name='unidade_embalagem',
            field=models.CharField(blank=True, choices=[('g', 'Grama'), ('kg', 'Quilograma'), ('ml', 'Mililitro'), ('L', 'Litro')], max_length=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='itemgenerico',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conteudo_embalagem__isnull', True), ('unidade_embalagem__isnull', True)), models.Q(('conteudo_embalagem__gt', 0), ('unidade_embalagem__in', ['g', 'kg', 'ml', 'L'])), _connector='OR'), name='item_generico_embalagem_coerente'),
        ),
    ]
