# Generated by Django 6.0.2 on 2026-09-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rbac_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('DIRET', 'Diretor'), ('TECAD', 'Técnico Administrativo'), ('NUTRI', 'Nutricionista'), ('ESTOQ', 'Estoquista')], default='TECAD', max_length=5),
        ),
    ]
