# Generated by Django 6.0.2 on 2026-03-14 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licitacao', models.CharField(max_length=50, unique=True, verbose_name='Número da Licitação')),
                ('validade', models.IntegerField(verbose_name='Validade (em meses)')),
                ('data_abertura', models.DateField(verbose_name='Data de Abertura')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Licitação')),
            ],
        ),
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ata', models.CharField(max_length=50, unique=True, verbose_name='Número da Ata')),
                ('ata_saldo_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Total da Ata')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.fornecedor')),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacao.licitacao')),
            ],
            options={
                'unique_together': {('licitacao', 'fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='ItemAta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255, verbose_name='Marca do Item')),
                ('quantidade_licitada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Licitada')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacao.ata')),
                ('item_generico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.itemgenerico')),
            ],
        ),
    ]
