# Generated by Django 6.0.2 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='atual',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Licitação atual'),
        ),
    ]
