# Generated by Django 6.0.2 on 2026-09-27 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_triggers_imutabilidade(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    schema_editor.execute("""
        CREATE TRIGGER trg_mov_estoque_bloqueia_update
        BEFORE UPDATE ON estoque_movimentacaoestoque
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Movimentacao de estoque e imutavel: use estorno.'
    """)
    schema_editor.execute("""
        CREATE TRIGGER trg_mov_estoque_bloqueia_delete
        BEFORE DELETE ON estoque_movimentacaoestoque
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Movimentacao de estoque e imutavel: use estorno.'
    """)


def remover_triggers_imutabilidade(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    schema_editor.execute('DROP TRIGGER IF EXISTS trg_mov_estoque_bloqueia_update')
    schema_editor.execute('DROP TRIGGER IF EXISTS trg_mov_estoque_bloqueia_delete')


def criar_estoques_existentes(apps, schema_editor):
    ItemGenerico = apps.get_model('cadastro', 'ItemGenerico')
    Estoque = apps.get_model('estoque', 'Estoque')
    Estoque.objects.bulk_create(
        [Estoque(item_generico_id=item_id) for item_id in ItemGenerico.objects.values_list('id', flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    initial = True
    atomic = False

    dependencies = [
        ('cadastro', '0002_itemgenerico_conteudo_embalagem_and_more'),
        ('entrega', '0001_initial'),
        ('usuario', '0003_alter_usuario_papel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('item_generico', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estoque', to='cadastro.itemgenerico')),
            ],
            options={
                'ordering': ['item_generico__descricao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARGA_INICIAL', 'Carga inicial'), ('PERIODICO', 'Periódico')], max_length=20)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=20)),
                ('data_contagem', models.DateTimeField()),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=500, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_contagem', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_sistema', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_contada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='estoque.estoque')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='estoque.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA_FORNECEDOR', 'Entrada de fornecedor'), ('CARGA_INICIAL', 'Carga inicial'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('SAIDA_PRODUCAO', 'Saída para produção'), ('SAIDA_DOACAO', 'Saída para doação'), ('SAIDA_PERDA', 'Saída por perda'), ('ESTORNO', 'Estorno')], max_length=20)),
                ('sentido', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('saldo_resultante', models.DecimalField(decimal_places=3, max_digits=12)),
                ('data_hora', models.DateTimeField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('papel', models.CharField(max_length=5)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.estoque')),
                ('item_inventario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacao_estoque', to='estoque.iteminventario')),
                ('item_ordem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacao_estoque', to='entrega.itemordem')),
                ('movimentacao_estornada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estorno', to='estoque.movimentacaoestoque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_atual__gte', 0)), name='estoque_saldo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('data_finalizacao__isnull', True), ('status', 'ABERTO')), models.Q(('data_finalizacao__isnull', False), ('status', 'FINALIZADO')), _connector='OR'), name='inventario_status_finalizacao_coerente'),
        ),
        migrations.AddConstraint(
            model_name='iteminventario',
            constraint=models.UniqueConstraint(fields=('inventario', 'estoque'), name='item_inventario_unico_por_estoque'),
        ),
        migrations.AddConstraint(
            model_name='iteminventario',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_sistema__gte', 0), ('quantidade_contada__gte', 0)), name='item_inventario_quantidades_nao_negativas'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['estoque', 'data_hora'], name='mov_estoque_data_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tipo', 'data_hora'], name='mov_tipo_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='mov_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_resultante__gte', 0)), name='mov_saldo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sentido', 'E'), ('tipo__in', ['ENTRADA_FORNECEDOR', 'CARGA_INICIAL', 'AJUSTE_POSITIVO'])), models.Q(('sentido', 'S'), ('tipo__in', ['AJUSTE_NEGATIVO', 'SAIDA_PRODUCAO', 'SAIDA_DOACAO', 'SAIDA_PERDA'])), ('tipo', 'ESTORNO'), _connector='OR'), name='mov_sentido_por_tipo'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_ordem__isnull', False), ('tipo', 'ENTRADA_FORNECEDOR')), models.Q(models.Q(('tipo', 'ENTRADA_FORNECEDOR'), _negated=True), ('item_ordem__isnull', True)), _connector='OR'), name='mov_entrada_exige_item_ordem'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_inventario__isnull', False), ('tipo__in', ['CARGA_INICIAL', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO'])), models.Q(models.Q(('tipo__in', ['CARGA_INICIAL', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO']), _negated=True), ('item_inventario__isnull', True)), _connector='OR'), name='mov_ajuste_exige_item_inventario'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movimentacao_estornada__isnull', False), ('tipo', 'ESTORNO')), models.Q(models.Q(('tipo', 'ESTORNO'), _negated=True), ('movimentacao_estornada__isnull', True)), _connector='OR'), name='mov_estorno_exige_origem'),
        ),
        migrations.RunPython(criar_estoques_existentes, migrations.RunPython.noop),
        migrations.RunPython(criar_triggers_imutabilidade, remover_triggers_imutabilidade),
    ]
