# Generated by Django 6.0.2 on 2026-09-27 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'ENTRADA_FORNECEDOR'), models.Q(('observacao__isnull', False), models.Q(('observacao', ''), _negated=True)), _connector='OR'), name='mov_observacao_obrigatoria'),
        ),
    ]
