# Generated by Django 6.0.2 on 2026-09-27 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0002_alter_ordementrega_status'),
        ('estoque', '0002_movimentacaoestoque_mov_observacao_obrigatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='item_ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='entrega.itemordem'),
        ),
    ]
