# Generated by Django 6.0.2 on 2026-03-14 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empenho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('esp', 'Em espera'), ('con', 'Concluída')], default='esp', max_length=3)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateTimeField()),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('valor_total_executado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empenho.empenho')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_entregue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('item_empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empenho.itemempenho')),
                ('ordem_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.ordementrega')),
            ],
        ),
    ]
