# Generated by Django 6.0.2 on 2026-09-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordementrega',
            name='status',
            field=models.CharField(choices=[('esp', 'Em espera'), ('par', 'Parcialmente entregue'), ('con', 'Concluída')], default='esp', max_length=3),
        ),
    ]
