# Generated by Django 6.0.2 on 2026-03-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordementrega',
            name='data_entrega_prevista',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordementrega',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordementrega',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
