# Generated by Django 6.0.2 on 2026-09-27 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0002_alter_ordementrega_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordementrega',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PendenciaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pendente', models.DecimalField(decimal_places=3, max_digits=12)),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('CIENTE', 'Ciente'), ('RESOLVIDA', 'Resolvida')], default='ABERTA', max_length=10)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_ciencia', models.DateTimeField(blank=True, null=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('ciente_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_cientes', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_recebidas', to=settings.AUTH_USER_MODEL)),
                ('item_ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='entrega.itemordem')),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_atualizacao', '-id'],
            },
        ),
    ]
