# Generated by Django 6.0.2 on 2026-03-14 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo do Empenho')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Empenho')),
                ('saldo_utilizado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Utilizado do Empenho')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacao.ata')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Atual do Item no Empenho')),
                ('quantidade_entrege', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Entregue do Item no Empenho')),
                ('empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empenho.empenho')),
                ('item_ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacao.itemata')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inc', 'Inclusão (Inc)'), ('ref', 'Reforço (Ref)'), ('anl', 'Anulação (Anl)')], max_length=3, verbose_name='Tipo de Operação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Operação')),
                ('data', models.DateTimeField(verbose_name='Data da Operação')),
                ('item_empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empenho.itemempenho')),
            ],
        ),
    ]
