# Generated by Django 6.0.2 on 2026-09-27 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenho', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoReforco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATENDIDA', 'Atendida'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('resposta', models.TextField(blank=True, default='')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('item_empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_reforco', to='empenho.itemempenho')),
                ('operacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_reforco', to='empenho.operacaoitem')),
                ('respondida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_reforco_respondidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_reforco', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_solicitacao', '-id'],
            },
        ),
    ]
