# Generated by Django 6.0.2 on 2026-03-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemempenho',
            name='quantidade_entrege',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Entregue do Item no Empenho'),
            preserve_default=False,
        ),
    ]
