# Generated by Django 6.0.2 on 2026-03-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenho', '0002_itemempenho_quantidade_entrege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaoitem',
            name='data',
            field=models.DateTimeField(verbose_name='Data da Operação'),
        ),
    ]
