# Generated by Django 6.0.2 on 2026-09-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenho', '0002_solicitacao_reforco'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoreforco',
            name='vista_pelo_solicitante',
            field=models.BooleanField(default=True),
        ),
    ]
