# Generated by Django 6.0.2 on 2026-10-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenho', '0003_solicitacao_reforco_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaoitem',
            name='ciente_tecnico',
            field=models.BooleanField(default=True),
        ),
    ]
