FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG API_URL=/api/v1
ENV API_URL=${API_URL}

RUN npm run build:render

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist/sige-app/browser /usr/share/nginx/html

EXPOSE 10000
